[build]
builder = "nixpacks"
buildCommand = "npm run build"

[nixpacks]
install_cmd = "npm install --legacy-peer-deps"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production" 