export default {
  extends: [
    'stylelint-config-standard',
    'stylelint-config-prettier',
    'stylelint-config-standard-scss'
  ],
  ignoreFiles: [
    'dist/**/*',
    'node_modules/**/*',
    '*.js',
    '*.ts',
    '*.jsx',
    '*.tsx'
  ],
  rules: {
    'at-rule-no-unknown': null,
    'scss/at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: [
          'tailwind',
          'apply',
          'variants',
          'responsive',
          'screen',
          'layer',
          'function',
          'if',
          'each',
          'include',
          'mixin',
          'use',
          'forward',
          'sp',
          'pc',
          'tab',
          'tab-vertical'
        ]
      }
    ],
    'declaration-block-trailing-semicolon': null,
    'no-descending-specificity': null,
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['global', 'deep', 'v-deep']
      }
    ],
    'property-no-unknown': [
      true,
      {
        ignoreProperties: ['font-named-instance', '/^--/']
      }
    ],
    'unit-allowed-list': [
      'em',
      'rem',
      'px',
      '%',
      'deg',
      's',
      'ms',
      'vh',
      'vw',
      'vmin',
      'vmax',
      'fr',
      'ch',
      'ex',
      'cm',
      'mm',
      'in',
      'pt',
      'pc',
      'dpi',
      'dpcm',
      'dppx'
    ],
    'value-keyword-case': null,
    'no-invalid-position-at-import-rule': null,
    'declaration-empty-line-before': null,
    'custom-property-empty-line-before': null,
    'selector-class-pattern': null,
    'custom-property-pattern': null,
    'keyframes-name-pattern': null,
    'no-missing-end-of-source-newline': null,
    'string-quotes': null,
    'function-url-quotes': null,
    'font-family-name-quotes': null,
    'color-function-notation': null,
    'alpha-value-notation': null,
    'value-no-vendor-prefix': null,
    'property-no-vendor-prefix': null,
    'selector-no-vendor-prefix': null,
    'media-feature-name-no-vendor-prefix': null,
    'at-rule-no-vendor-prefix': null,
    'scss/double-slash-comment-empty-line-before': null,
    'scss/dollar-variable-pattern': null,
    'scss/at-mixin-pattern': null,
    'scss/percent-placeholder-pattern': null,
    'scss/at-function-pattern': null,
    'scss/at-extend-no-missing-placeholder': null,
    'scss/at-import-no-partial-leading-underscore': null,
    'scss/at-import-partial-extension': null,
    'scss/operator-no-unspaced': null,
    'scss/operator-no-newline-after': null,
    'scss/selector-no-redundant-nesting-selector': null,
    'scss/no-duplicate-mixins': null,
    'scss/no-global-function-names': null,
    'scss/comment-no-empty': null,
    'scss/dollar-variable-empty-line-before': null,
    'scss/double-slash-comment-whitespace-inside': null,
    'scss/declaration-nested-properties': null,
    'scss/dimension-no-non-numeric-values': null,
    'scss/function-quote-no-quoted-strings-inside': null,
    'scss/function-unquote-no-unquoted-strings-inside': null,
    'scss/map-keys-quotes': null,
    'scss/selector-nest-combinators': null,
    'scss/selector-no-union-class-name': null,
    'scss/no-duplicate-dollar-variables': null,
    'scss/at-if-no-null': null,
    'scss/at-each-key-value-single-line': null,
    'scss/at-else-empty-line-before': null,
    'scss/at-else-if-parentheses-space-before': null,
    'scss/at-function-parentheses-space-before': null,
    'scss/at-mixin-argumentless-call-parentheses': null,
    'scss/at-mixin-parentheses-space-before': null,
    'scss/dollar-variable-colon-space-after': null,
    'scss/dollar-variable-colon-space-before': null,
    'scss/dollar-variable-no-missing-interpolation': null,
    'scss/function-color-relative': null,
    'scss/partial-no-import': null,
    'scss/at-rule-conditional-no-parentheses': null,
    'scss/comment-no-loud': null,
    'scss/function-no-unknown': [
      true,
      {
        ignoreFunctions: ['vw', 'vw_sp', 'vw_pc', 'tab', 'tab-vertical', 'darkBlue', 'sixcaps']
      }
    ],
    'scss/media-feature-value-dollar-variable': null,
    'scss/declaration-nested-properties-no-divided-groups': null,
    'scss/dollar-variable-default': null,
    'scss/dollar-variable-first-in-block': null,
    'scss/load-no-partial-leading-underscore': null,
    'scss/operator-no-newline-before': null,
    'scss/no-global-function-names': null,
    'scss/dollar-variable-empty-line-before': null,
    'scss/double-slash-comment-whitespace-inside': null,
    'scss/declaration-nested-properties': null,
    'scss/dimension-no-non-numeric-values': null,
    'scss/function-quote-no-quoted-strings-inside': null,
    'scss/function-unquote-no-unquoted-strings-inside': null,
    'scss/map-keys-quotes': null,
    'scss/selector-nest-combinators': null,
    'scss/selector-no-union-class-name': null,
    'scss/at-if-no-null': null,
    'scss/at-each-key-value-single-line': null,
    'scss/at-else-empty-line-before': null,
    'scss/at-else-if-parentheses-space-before': null,
    'scss/at-function-parentheses-space-before': null,
    'scss/at-mixin-argumentless-call-parentheses': null,
    'scss/at-mixin-parentheses-space-before': null,
    'scss/dollar-variable-colon-space-after': null,
    'scss/dollar-variable-colon-space-before': null,
    'scss/dollar-variable-no-missing-interpolation': null,
    'scss/function-color-relative': null,
    'scss/partial-no-import': null,
    'scss/at-rule-conditional-no-parentheses': null,
    'scss/comment-no-loud': null,
    'scss/media-feature-value-dollar-variable': null,
    'scss/declaration-nested-properties-no-divided-groups': null,
    'scss/dollar-variable-default': null,
    'scss/dollar-variable-first-in-block': null,
    'scss/load-no-partial-leading-underscore': null,
    'scss/operator-no-newline-before': null,
    'scss/no-global-function-names': null,
    'scss/dollar-variable-empty-line-before': null,
    'scss/double-slash-comment-whitespace-inside': null,
    'scss/declaration-nested-properties': null,
    'scss/dimension-no-non-numeric-values': null,
    'scss/function-quote-no-quoted-strings-inside': null,
    'scss/function-unquote-no-unquoted-strings-inside': null,
    'scss/map-keys-quotes': null,
    'scss/selector-nest-combinators': null,
    'scss/selector-no-union-class-name': null,
    'scss/at-if-no-null': null,
    'scss/at-each-key-value-single-line': null,
    'scss/at-else-empty-line-before': null,
    'scss/at-else-if-parentheses-space-before': null,
    'scss/at-function-parentheses-space-before': null,
    'scss/at-mixin-argumentless-call-parentheses': null,
    'scss/at-mixin-parentheses-space-before': null,
    'scss/dollar-variable-colon-space-after': null,
    'scss/dollar-variable-colon-space-before': null,
    'scss/dollar-variable-no-missing-interpolation': null,
    'scss/function-color-relative': null,
    'scss/partial-no-import': null,
    'scss/at-rule-conditional-no-parentheses': null,
    'scss/comment-no-loud': null,
    'scss/media-feature-value-dollar-variable': null,
    'scss/declaration-nested-properties-no-divided-groups': null,
    'scss/dollar-variable-default': null,
    'scss/dollar-variable-first-in-block': null,
    'scss/load-no-partial-leading-underscore': null,
    'scss/operator-no-newline-before': null
  }
}
